apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2017-08-11T04:17:03Z
    generation: 1
    labels:
      run: iibmq1
    name: iibmq1
    namespace: default
    resourceVersion: "1080"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/iibmq1
    uid: edc12919-7e4b-11e7-a42c-6a9371d0b51b
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: iibmq1
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: iibmq1
      spec:
        containers:
        - env:
          - name: LICENSE
            value: accept
          - name: MQ_QMGR_NAME
            value: QM1
          image: registry.ng.bluemix.net/iib-mq:2
          imagePullPolicy: IfNotPresent
          name: iibmq1
          ports:
          - containerPort: 4414
          - containerPort: 9443
          - containerPort: 7800
          - containerPort: 1414
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2017-08-11T04:17:03Z
      lastUpdateTime: 2017-08-11T04:17:03Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    replicas: 1
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
